export default {
    MARK_NOTIFICATIONS_AS_READ_BY_ID : 'MARK_NOTIFICATIONS_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS_AS_READ_BY_ID : 'MARK_ALL_NOTIFICATIONS_AS_READ_BY_ID',
    START_MARK_AS_READ: 'START_MARK_AS_READ',
    FINISH_MARK_AS_READ: 'FINISHI_MARK_AS_READ',
    RECEIVED_NOTIFICATIONS:'RECEIVED_NOTIFICATIONS'
}

